"""
backtest.py
===========
Historical simulation of the Bull Call Spread analysis system.

Simulates 1 year of daily market analysis using historical price data
from yfinance. For each trading day, runs criteria + scoring as if
operating on that date, then checks 30 days later if the trade
would have been profitable.

Features:
    - Checkpoint system: saves progress to DB — resumable after interruption
    - Retry logic: handles network failures gracefully
    - Progress tracking: shows ETA and completion percentage
    - Detailed logging: errors saved to backtest_errors.log
    - Outcomes: automatically records what happened 30 days after each signal
    - S&P 500: reads full 503-ticker list from sp500_tickers.json

Usage:
    python backtest.py                          → run full 1-year backtest (S&P 500)
    python backtest.py --tickers AAPL MSFT      → specific tickers only
    python backtest.py --resume                 → continue interrupted backtest
    python backtest.py --days 180               → last 180 days only
    python backtest.py --summary                → show results without running

Dependencies:
    criteria.py         → market data calculation
    scoring.py          → scoring and verdict
    db.py               → save results to PostgreSQL
    sp500_tickers.json  → full S&P 500 ticker list with sectors
    .env                → DATABASE_URL
"""

import os
import sys
import json
import time
import logging
import argparse
from datetime import datetime, date, timedelta

import pandas as pd
import yfinance as yf
from dotenv import load_dotenv

from scoring import score_criteria
from db import (
    save_backtest_analysis,
    get_backtest_progress,
    get_backtest_results,
    save_outcome,
    get_connection
)

load_dotenv()

# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

# Path to S&P 500 tickers JSON (generated by get_sp500_tickers.py)
SP500_JSON = "sp500_tickers.json"

# Fallback list if JSON not found
DEFAULT_TICKERS = [
    "AAPL", "MSFT", "GOOGL", "META", "AMZN", "NVDA",
    "JPM", "BAC", "GS", "V", "MA",
    "HD", "WMT", "COST", "MCD", "NKE",
    "JNJ", "UNH",
    "SPY", "QQQ",
]

# How many days back to simulate
DEFAULT_LOOKBACK_DAYS = 365

# Days after signal to check outcome
OUTCOME_DAYS = 30

# Minimum data points needed for reliable indicators
MIN_DATA_POINTS = 60  # ~SMA200 + buffer

# Retry configuration
MAX_RETRIES    = 3
RETRY_DELAY    = 5   # seconds between retries
API_DELAY      = 0.3 # seconds between yfinance calls (rate limiting)

# Log file
LOG_FILE = "backtest_errors.log"


# ══════════════════════════════════════════════════════════════════════════════
# S&P 500 TICKER LOADING
# ══════════════════════════════════════════════════════════════════════════════

def load_sp500_tickers():
    """
    Load full S&P 500 ticker list from sp500_tickers.json.
    Returns a dict: { ticker: sector } for all 503 tickers.
    Falls back to DEFAULT_TICKERS with sector=None if JSON not found.
    """
    if not os.path.exists(SP500_JSON):
        print(f"  ⚠️  {SP500_JSON} not found — using default {len(DEFAULT_TICKERS)} tickers")
        return {t: None for t in DEFAULT_TICKERS}

    with open(SP500_JSON, "r") as f:
        data = json.load(f)

    # Build ticker -> sector map from by_sector dict
    ticker_sector = {}
    for sector, tickers in data["by_sector"].items():
        for ticker in tickers:
            ticker_sector[ticker] = sector

    print(f"  ✅ Loaded {len(ticker_sector)} tickers from {SP500_JSON}")

    # Print sector breakdown
    from collections import Counter
    sector_counts = Counter(ticker_sector.values())
    for sector, count in sorted(sector_counts.items(), key=lambda x: -x[1]):
        print(f"     {count:3d}  {sector}")

    return ticker_sector


# ══════════════════════════════════════════════════════════════════════════════
# LOGGING
# ══════════════════════════════════════════════════════════════════════════════

logging.basicConfig(
    filename=LOG_FILE,
    level=logging.ERROR,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

def log_error(ticker, date_str, error):
    """Log error to file without crashing the script."""
    logging.error(f"{ticker} | {date_str} | {error}")


# ══════════════════════════════════════════════════════════════════════════════
# TRADING DAYS
# ══════════════════════════════════════════════════════════════════════════════

def get_trading_days(start, end):
    """Return list of weekdays between start and end (approx trading days)."""
    days = []
    current = start
    while current <= end:
        if current.weekday() < 5:  # Mon–Fri
            days.append(current)
        current += timedelta(days=1)
    return days


# ══════════════════════════════════════════════════════════════════════════════
# CRITERIA CACHE (avoid repeated API calls per ticker)
# ══════════════════════════════════════════════════════════════════════════════

_fundamentals_cache = {}
_beta_cache         = {}
_earnings_cache     = {}

def _get_fundamentals_cached(ticker):
    from criteria import get_fundamentals
    if ticker not in _fundamentals_cache:
        _fundamentals_cache[ticker] = get_fundamentals(ticker)
    return _fundamentals_cache[ticker]

def _get_beta_cached(ticker):
    from criteria import get_beta
    if ticker not in _beta_cache:
        _beta_cache[ticker] = get_beta(ticker)
    return _beta_cache[ticker]

def _get_earnings_near_date(ticker, ref_date):
    from criteria import get_earnings_info
    if ticker not in _earnings_cache:
        _earnings_cache[ticker] = get_earnings_info(ticker)
    return _earnings_cache[ticker]


# ══════════════════════════════════════════════════════════════════════════════
# OUTCOME CALCULATION
# ══════════════════════════════════════════════════════════════════════════════

def calculate_outcome(full_data, entry_date, entry_price):
    """
    Calculate what happened 30 days after entry.
    Uses pre-downloaded historical data — no extra API calls needed.

    Args:
        full_data   (pd.DataFrame) — full historical OHLCV data
        entry_date  (date)         — date of the simulated trade
        entry_price (float)        — price at entry

    Returns:
        dict with keys:
            price_at_30d        (float | None)
            pct_change_30d      (float | None)
            would_have_profited (bool | None)
    """
    target_date = entry_date + timedelta(days=OUTCOME_DAYS)

    # Find closest available trading day at or after target_date
    future_data = full_data[full_data.index.date >= target_date]

    if future_data.empty:
        return {
            "price_at_30d":        None,
            "pct_change_30d":      None,
            "would_have_profited": None
        }

    price_30d  = float(future_data["Close"].squeeze().iloc[0])
    pct_change = round((price_30d - entry_price) / entry_price * 100, 4)

    return {
        "price_at_30d":        round(price_30d, 2),
        "pct_change_30d":      pct_change,
        "would_have_profited": pct_change > 0
    }


# ══════════════════════════════════════════════════════════════════════════════
# PROGRESS DISPLAY
# ══════════════════════════════════════════════════════════════════════════════

def print_progress(current, total, ticker, current_date, start_time, errors):
    """Print a progress bar with ETA."""
    pct       = current / total * 100
    elapsed   = time.time() - start_time
    rate      = current / elapsed if elapsed > 0 else 0
    remaining = (total - current) / rate if rate > 0 else 0

    eta_min = int(remaining // 60)
    eta_sec = int(remaining % 60)

    bar_width = 30
    filled    = int(bar_width * current / total)
    bar       = "█" * filled + "░" * (bar_width - filled)

    sys.stdout.write(
        f"\r  [{bar}] {pct:.1f}% | "
        f"{current}/{total} | "
        f"{ticker} {current_date} | "
        f"ETA: {eta_min}m {eta_sec}s | "
        f"Errors: {errors}"
    )
    sys.stdout.flush()


# ══════════════════════════════════════════════════════════════════════════════
# MAIN BACKTEST
# ══════════════════════════════════════════════════════════════════════════════

def run_backtest(tickers, lookback_days=DEFAULT_LOOKBACK_DAYS, resume=False, ticker_sector=None):
    """
    Run the full historical simulation.

    Pipeline per ticker:
        1. Download full historical data (lookback + buffer)
        2. Find resume point if --resume mode
        3. For each trading day:
            a. Slice data to that date
            b. Calculate criteria
            c. Score criteria
            d. Save to DB with is_backtest=True and sector
            e. Calculate 30-day outcome
            f. Save outcome to DB
        4. Print summary

    Args:
        tickers       (list)       — tickers to simulate
        lookback_days (int)        — how many days back to simulate
        resume        (bool)       — skip already-processed dates
        ticker_sector (dict|None)  — map of ticker -> sector
    """
    if ticker_sector is None:
        ticker_sector = {t: None for t in tickers}

    end_date   = date.today() - timedelta(days=1)
    start_date = end_date - timedelta(days=lookback_days)

    # Need extra data for SMA200 calculation
    data_start = start_date - timedelta(days=MIN_DATA_POINTS + 30)

    trading_days = get_trading_days(start_date, end_date)
    total_steps  = len(tickers) * len(trading_days)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    print(f"\n{'═' * 65}")
    print(f"  BACKTEST — {timestamp}")
    print(f"  Period:   {start_date} → {end_date} ({len(trading_days)} trading days)")
    print(f"  Tickers:  {len(tickers)}")
    print(f"  Total:    {total_steps:,} analysis points")
    print(f"  Mode:     {'RESUME' if resume else 'FULL'}")
    print(f"  ETA:      ~{total_steps * 1.5 / 3600:.1f} hours estimated")
    print(f"{'═' * 65}\n")

    if sys.stdin.isatty():
        input("  Press Enter to start (Ctrl+C to stop at any time)...")
    else:
        print("  Running in non-interactive mode — starting automatically...")
    print()

    start_time    = time.time()
    current_step  = 0
    total_errors  = 0
    total_saved   = 0
    total_skipped = 0

    for ticker in tickers:
        sector = ticker_sector.get(ticker)
        sector_label = f"[{sector}]" if sector else ""
        print(f"\n\n  ── {ticker} {sector_label} {'─' * max(1, 48 - len(ticker) - len(sector_label))}")

        # ── Download full historical data ─────────────────────────────────────
        print(f"  📥 Downloading {ticker} historical data...", end=" ", flush=True)

        full_data = None
        for attempt in range(MAX_RETRIES):
            try:
                full_data = yf.download(
                    ticker,
                    start=data_start,
                    end=end_date + timedelta(days=OUTCOME_DAYS + 10),
                    interval="1d",
                    progress=False,
                    auto_adjust=True
                )
                if not full_data.empty:
                    break
            except Exception as e:
                if attempt < MAX_RETRIES - 1:
                    time.sleep(RETRY_DELAY)

        if full_data is None or full_data.empty:
            print(f"❌ Failed to download data — skipping {ticker}")
            log_error(ticker, "DOWNLOAD", "Failed to download historical data")
            current_step += len(trading_days)
            total_errors += 1
            continue

        print(f"✅ {len(full_data)} days downloaded")

        # ── Find resume point ─────────────────────────────────────────────────
        resume_from = None
        if resume:
            last_date = get_backtest_progress(ticker)
            if last_date:
                resume_from = last_date
                skipped = sum(1 for d in trading_days if d <= last_date)
                total_skipped += skipped
                print(f"  ⏭️  Resuming from {last_date} ({skipped} days skipped)")

        # ── Pre-fetch static data once per ticker ─────────────────────────────
        print(f"  📊 Pre-fetching fundamentals and beta...", end=" ", flush=True)
        _get_fundamentals_cached(ticker)
        _get_beta_cached(ticker)
        _get_earnings_near_date(ticker, start_date)
        print("✅")

        # ── Process each trading day ──────────────────────────────────────────
        ticker_saved  = 0
        ticker_errors = 0

        for sim_date in trading_days:
            current_step += 1

            # Skip if resuming and already processed
            if resume_from and sim_date <= resume_from:
                continue

            print_progress(
                current_step, total_steps, ticker,
                sim_date, start_time, total_errors
            )

            # ── Calculate criteria for this date ──────────────────────────────
            from criteria import get_historical_criteria

            criteria = None
            for attempt in range(MAX_RETRIES):
                try:
                    criteria = get_historical_criteria(ticker, sim_date, full_data)
                    if criteria is None:
                        break
                    break
                except Exception as e:
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(RETRY_DELAY)
                    else:
                        log_error(ticker, str(sim_date), f"criteria: {e}")
                        ticker_errors += 1

            if criteria is None:
                continue

            # ── Score criteria ────────────────────────────────────────────────
            scored = None
            try:
                scored = score_criteria(criteria)
            except Exception as e:
                log_error(ticker, str(sim_date), f"scoring: {e}")
                ticker_errors += 1
                continue

            if scored is None:
                continue

            # ── Save to DB (with sector) ──────────────────────────────────────
            analysis_id = None
            for attempt in range(MAX_RETRIES):
                try:
                    analysis_id = save_backtest_analysis(scored, sim_date, sector=sector)
                    break
                except Exception as e:
                    if attempt < MAX_RETRIES - 1:
                        time.sleep(2)
                    else:
                        log_error(ticker, str(sim_date), f"db save: {e}")
                        ticker_errors += 1

            if analysis_id is None:
                continue

            # ── Calculate and save outcome ────────────────────────────────────
            try:
                outcome = calculate_outcome(full_data, sim_date, criteria["price"])

                if outcome["price_at_30d"] is not None:
                    save_outcome(
                        analysis_id=analysis_id,
                        ticker=ticker,
                        price_at_analysis=criteria["price"],
                        price_at_30d=outcome["price_at_30d"],
                        price_at_expiry=outcome["price_at_30d"]
                    )
            except Exception as e:
                log_error(ticker, str(sim_date), f"outcome: {e}")

            ticker_saved += 1
            total_saved  += 1

            # Small delay to avoid overwhelming yfinance
            time.sleep(API_DELAY)

        total_errors += ticker_errors
        print(f"\n  ✅ {ticker}: {ticker_saved} days saved, {ticker_errors} errors")

    # ── Final summary ─────────────────────────────────────────────────────────
    elapsed_min = int((time.time() - start_time) // 60)
    elapsed_sec = int((time.time() - start_time) % 60)

    print(f"\n\n{'═' * 65}")
    print(f"  BACKTEST COMPLETE")
    print(f"{'═' * 65}")
    print(f"  Total saved:   {total_saved:,} analysis points")
    print(f"  Total skipped: {total_skipped:,} (resume mode)")
    print(f"  Total errors:  {total_errors}")
    print(f"  Duration:      {elapsed_min}m {elapsed_sec}s")
    if total_errors > 0:
        print(f"  Error log:     {LOG_FILE}")
    print(f"{'═' * 65}\n")

    print_summary()


# ══════════════════════════════════════════════════════════════════════════════
# SUMMARY — quick stats without running backtest
# ══════════════════════════════════════════════════════════════════════════════

def print_summary():
    """Print summary statistics from backtest results in DB."""
    print(f"\n{'═' * 65}")
    print(f"  BACKTEST RESULTS SUMMARY")
    print(f"{'═' * 65}")

    conn = get_connection()
    cur  = conn.cursor()

    cur.execute("SELECT COUNT(*) FROM analysis WHERE is_backtest = TRUE;")
    total = cur.fetchone()[0]

    if total == 0:
        print("  No backtest data found. Run backtest first.")
        cur.close()
        conn.close()
        return

    cur.execute("""
        SELECT verdict, COUNT(*) as cnt
        FROM analysis
        WHERE is_backtest = TRUE
        GROUP BY verdict
        ORDER BY cnt DESC;
    """)
    verdicts = cur.fetchall()

    print(f"  Total analysis points: {total:,}")
    print(f"\n  By verdict:")
    for verdict, cnt in verdicts:
        pct = cnt / total * 100
        print(f"    {verdict:<15} {cnt:>6,}  ({pct:.1f}%)")

    # Win rate for VIABLE signals
    cur.execute("""
        SELECT
            COUNT(*) as total_viable,
            SUM(CASE WHEN o.would_have_profited = TRUE THEN 1 ELSE 0 END) as wins,
            AVG(o.pct_change_30d) as avg_return
        FROM analysis a
        JOIN outcomes o ON o.analysis_id = a.id
        WHERE a.is_backtest = TRUE AND a.verdict = 'VIABLE';
    """)
    row = cur.fetchone()
    if row and row[0]:
        total_v, wins, avg_ret = row
        win_rate = wins / total_v * 100 if total_v > 0 else 0
        print(f"\n  VIABLE signals with outcomes:")
        print(f"    Total:    {total_v:,}")
        print(f"    Win rate: {win_rate:.1f}%")
        print(f"    Avg return (30d): {avg_ret:.2f}%")

    # Breakdown by sector (if available)
    cur.execute("""
        SELECT sector, COUNT(*) as cnt,
               SUM(CASE WHEN verdict = 'VIABLE' THEN 1 ELSE 0 END) as viable
        FROM analysis
        WHERE is_backtest = TRUE AND sector IS NOT NULL
        GROUP BY sector
        ORDER BY cnt DESC;
    """)
    sector_rows = cur.fetchall()

    if sector_rows:
        print(f"\n  By sector:")
        print(f"    {'Sector':<35} {'Total':>7}  {'VIABLE':>7}  {'VIABLE%':>8}")
        print(f"    {'─' * 60}")
        for sector, cnt, viable in sector_rows:
            viable_pct = viable / cnt * 100 if cnt > 0 else 0
            print(f"    {sector:<35} {cnt:>7,}  {viable:>7,}  {viable_pct:>7.1f}%")

    cur.close()
    conn.close()
    print(f"\n{'═' * 65}\n")


# ══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Historical backtest of Bull Call Spread analysis system"
    )
    parser.add_argument(
        "--tickers",
        nargs="+",
        default=None,
        help="Specific tickers to backtest (default: full S&P 500 from sp500_tickers.json)"
    )
    parser.add_argument(
        "--days",
        type=int,
        default=DEFAULT_LOOKBACK_DAYS,
        help="How many days back to simulate (default: 365)"
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume interrupted backtest from last checkpoint"
    )
    parser.add_argument(
        "--summary",
        action="store_true",
        help="Show results summary without running backtest"
    )
    args = parser.parse_args()

    if args.summary:
        print_summary()
    else:
        # Load full S&P 500 or use specified tickers
        if args.tickers:
            # Manual tickers specified — sector unknown unless in JSON
            sp500 = load_sp500_tickers()
            ticker_sector = {t: sp500.get(t) for t in args.tickers}
            tickers = args.tickers
        else:
            # Full S&P 500
            ticker_sector = load_sp500_tickers()
            tickers = list(ticker_sector.keys())

        try:
            run_backtest(
                tickers=tickers,
                lookback_days=args.days,
                resume=args.resume,
                ticker_sector=ticker_sector
            )
        except KeyboardInterrupt:
            print(f"\n\n  ⚠️  Backtest interrupted by user.")
            print(f"  Progress saved to DB. Resume with: python backtest.py --resume")
            print(f"  Partial results available with:    python backtest.py --summary\n")