"""
scanner.py
==========
Market opportunity scanner for options trading system.

Workflow:
    1. Reads market_context.json (generated by market_context.py)
    2. Fetches raw criteria for each ticker (no scoring, no numbers)
    3. Saves raw criteria to PostgreSQL
    4. Sends everything to AI in a single call:
         - Macro context (VIX, SPY, sectors)
         - Raw criteria per ticker (labels only)
         - Open positions
    5. AI recommends strategy per ticker and ranks opportunities
    6. Generates scanner_report.md (solo tickers aptos) y scanner_report.html (todos)

Usage:
    python scanner.py                          # default tickers
    python scanner.py --tickers AAPL MSFT CAT  # specific tickers
    python scanner.py --context                # tickers from market_context.json

Dependencies:
    criteria.py          → raw market data
    db.py                → save to PostgreSQL
    market_context.json  → macro context from market_context.py
    report_generator.py  → markdown + HTML reports
    .env                 → DATABASE_URL, ANTHROPIC_API_KEY
"""

import os
import sys
import json
import argparse
from datetime import datetime

import anthropic
from dotenv import load_dotenv

from criteria import get_all_criteria
from db import save_analysis, get_open_positions

load_dotenv()

sys.stdout.reconfigure(encoding="utf-8")

# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

DEFAULT_TICKERS = [
    "GOOGL", "META", "AMZN", "JPM", "GS",
    "HD", "WMT", "COST", "NKE", "MCD",
    "JNJ", "UNH", "SPY", "QQQ",
]

MARKET_CONTEXT_JSON = os.path.join(os.path.dirname(__file__), "market_context.json")

AI_MODEL      = "claude-opus-4-5"
AI_MAX_TOKENS = 3000

TRADING_CONTEXT = {
    "capital":      15000,
    "max_risk_pct": 2,
    "broker":       "Thinkorswim (paperMoney)",
    "is_paper":     True,
    "language":     "Spanish",
}


# ══════════════════════════════════════════════════════════════════════════════
# MARKET CONTEXT LOADER
# ══════════════════════════════════════════════════════════════════════════════

def load_market_context():
    """
    Load macro context from market_context.json.
    Returns None if file not found.
    """
    if not os.path.exists(MARKET_CONTEXT_JSON):
        return None

    with open(MARKET_CONTEXT_JSON) as f:
        data = json.load(f)

    return data


def format_market_context(ctx):
    """Format market context as readable string for AI prompt."""
    if not ctx:
        return "Market context not available — run market_context.py first."

    vix = ctx.get("vix", {})
    spy = ctx.get("spy", {})

    lines = [
        f"Generated: {ctx.get('timestamp', 'unknown')}",
        f"Verdict: {ctx.get('verdict', 'N/A')} — {ctx.get('verdict_detail', '')}",
        "",
        f"VIX: {vix.get('current', 'N/A')} ({vix.get('level', 'N/A')}, {vix.get('trend', 'N/A')})",
        f"     5d avg: {vix.get('avg_5d', 'N/A')} | 10d avg: {vix.get('avg_10d', 'N/A')}",
        "",
        f"SPY: ${spy.get('price', 'N/A')} | {spy.get('trend', 'N/A')} ({spy.get('pct_25d', 0):+.1f}% 25d)",
        f"     SMAs: {spy.get('sma_status', 'N/A')} | SMA50 {spy.get('sma50_dir', 'N/A')}",
        "",
        "Sector priorities (based on historical win rates):",
    ]

    for s in ctx.get("sectors", []):
        icon = "[OK]" if s["priority"] == "PRIORITY"   else \
               "[~]"  if s["priority"] == "ACCEPTABLE" else "[X]"
        lines.append(f"  {icon} {s['sector']:<35} {s['win_rate']:.1f}% win rate  [{s['priority']}]")

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# CRITERIA FORMATTER — labels only, no scores
# ══════════════════════════════════════════════════════════════════════════════

def format_criteria_for_ai(c):
    """
    Format raw criteria as readable context for AI.
    No scores — just meaningful labels and values.
    Matches exact structure returned by get_all_criteria().
    """
    lines = []

    # ── Technical ─────────────────────────────────────────────────────────────
    tech = c.get("technical", {})
    if tech:
        lines.append("TECHNICAL:")
        trend = tech.get("trend_25d", {})
        if trend:
            direction = "BULLISH" if trend.get("is_bullish") else "BEARISH"
            pct       = trend.get("pct_change", 0)
            lines.append(f"  Trend 25d:        {direction} ({pct:+.1f}%)")

        ma = tech.get("moving_averages", {})
        if ma:
            above = "Above both" if ma.get("above_sma50") and ma.get("above_sma200") \
                    else "Above SMA50" if ma.get("above_sma50") \
                    else "Below both"
            sma_dir = ma.get("sma50_direction", "N/A")
            lines.append(f"  Moving averages:  {above} | SMA50 {sma_dir}")

        rsi = tech.get("rsi")
        lines.append(f"  RSI:              {rsi:.1f}" if rsi is not None else "  RSI:              N/A")

        w52 = tech.get("week_52", {})
        if w52:
            pos = w52.get("position_pct", 0)
            tag = w52.get("tag", "")
            lines.append(f"  52-week:          {pos:.1f}% ({tag})")

        sr = tech.get("support_resistance", {})
        if sr:
            sup = sr.get("support_pct")
            res = sr.get("resistance_pct")
            lines.append(f"  Support:          {sup:.1f}% away"    if sup is not None else "  Support:          N/A")
            lines.append(f"  Resistance:       {res:.1f}% away"    if res is not None else "  Resistance:       N/A")

        candle = tech.get("candlestick", {})
        if candle:
            lines.append(f"  Candlestick:      {candle.get('pattern', 'N/A')} ({candle.get('sentiment', 'N/A')})")

    # ── Volatility ────────────────────────────────────────────────────────────
    vol = c.get("volatility", {})
    if vol:
        lines.append("VOLATILITY:")
        hv  = vol.get("hv_30d")
        iv  = vol.get("iv")
        ivp = vol.get("iv_percentile")
        beta = vol.get("beta")
        pcr  = vol.get("put_call_ratio")
        oi   = vol.get("open_interest")
        lines.append(f"  HV 30d:           {hv:.1f}%"       if hv   is not None else "  HV 30d:           N/A")
        lines.append(f"  IV:               {iv:.1f}% (P{ivp:.0f})" if iv is not None and ivp is not None else "  IV:               N/A")
        lines.append(f"  Beta:             {beta:.2f}"       if beta is not None else "  Beta:             N/A")
        lines.append(f"  Put/Call ratio:   {pcr:.2f}"        if pcr  is not None else "  Put/Call ratio:   N/A")
        lines.append(f"  Open interest:    {oi:,.0f}"        if oi   is not None else "  Open interest:    N/A")

    # ── Earnings ──────────────────────────────────────────────────────────────
    earn = c.get("earnings", {})
    if earn:
        lines.append("OPERATIONAL:")
        dte = earn.get("days_to_earnings")
        if dte:
            lines.append(f"  Earnings:         {dte}d")
        elif earn.get("is_etf"):
            lines.append("  Earnings:         ETF")
        else:
            lines.append("  Earnings:         N/A")

    # ── Volume ────────────────────────────────────────────────────────────────
    vol_data = c.get("volume", {})
    if vol_data:
        ratio = vol_data.get("volume_ratio_pct", 0)
        lines.append(f"  Volume:           {ratio:.0f}% of avg" if ratio else "  Volume:           N/A")

    # ── Fundamental ───────────────────────────────────────────────────────────
    fund = c.get("fundamental", {})
    if fund:
        lines.append("FUNDAMENTAL:")
        pe     = fund.get("pe")
        eps_g  = fund.get("eps_growth_pct")
        de     = fund.get("debt_to_equity")
        margin = fund.get("profit_margin_pct")
        lines.append(f"  PE ratio:         {pe:.1f}"    if pe     is not None else "  PE ratio:         N/A")
        lines.append(f"  EPS growth:       {eps_g:+.1f}%" if eps_g is not None else "  EPS growth:       N/A")
        lines.append(f"  Debt/equity:      {de:.2f}x"   if de     is not None else "  Debt/equity:      N/A")
        lines.append(f"  Profit margin:    {margin:.1f}%" if margin is not None else "  Profit margin:    N/A")

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# AI PROMPT
# ══════════════════════════════════════════════════════════════════════════════

def build_ai_prompt(all_criteria, open_positions, market_ctx, context):
    """
    Build AI prompt with:
    - Macro context (from market_context.json)
    - Raw criteria per ticker (labels only, no scores)
    - Open positions
    """
    # Format open positions
    if open_positions:
        pos_lines = []
        for p in open_positions:
            pos_lines.append(
                f"  {p['ticker']} | {p['strategy']} | "
                f"${p['strike_low']}/{p['strike_high']} | "
                f"Exp {p['expiration']} | Cost ${p['total_cost']}"
            )
        positions_str = "\n".join(pos_lines)
    else:
        positions_str = "None currently open."

    # Format all tickers
    tickers_str = ""
    for ticker, data in all_criteria.items():
        price = data.get("price", "N/A")
        tickers_str += f"\n{'─' * 50}\n"
        tickers_str += f"TICKER: {ticker} | Price: ${price:.2f}\n" if isinstance(price, (int, float)) else f"TICKER: {ticker}\n"
        tickers_str += format_criteria_for_ai(data)
        tickers_str += "\n"

    macro_str = format_market_context(market_ctx)

    prompt = f"""You are an expert options trading mentor. Your student is learning to trade options and wants to make decisions based on market context and technical analysis — not arbitrary numerical scores.

TRADING CONTEXT:
  Capital:        ${context['capital']:,}
  Max risk/trade: {context['max_risk_pct']}% (${context['capital'] * context['max_risk_pct'] // 100} max)
  Broker:         {context['broker']}
  Paper trading:  {context['is_paper']}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MACRO CONTEXT (from market_context.py):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{macro_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OPEN POSITIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{positions_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
TODAY'S TICKER ANALYSIS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{tickers_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INSTRUCTIONS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

For EACH ticker, provide a brief analysis with:
  STRATEGY: Which strategy fits best given the context?
    Options: Bull Call Spread / Bear Put Spread / Long Straddle / Cash Secured Put / Long Call / Long Put / No trade
  SETUP: Specific entry suggestion (strikes, expiration) if applicable
  RISK: Main risk to watch

Then provide:
  TOP 3: The 3 best opportunities today, ranked with reasoning
  OPEN POSITIONS: Assessment of current positions — hold, close, or watch?
  MARKET READ: In 2-3 sentences, what does the overall picture tell you about today?

Be direct, specific, and educational.
Base your analysis on the actual criteria values, not scores.
Consider the macro context when recommending strategies.
If the market context suggests caution, say so clearly.

IMPORTANT: Respond entirely in {context.get('language', 'Spanish')}.
Max 600 words total."""

    return prompt


def get_ai_interpretation(all_criteria, open_positions, market_ctx, context):
    """Single AI call with full context."""
    try:
        client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        prompt = build_ai_prompt(all_criteria, open_positions, market_ctx, context)

        print("\nGetting AI interpretation...")

        conversation_history = [{"role": "user", "content": prompt}]

        response = client.messages.create(
            model=AI_MODEL,
            max_tokens=AI_MAX_TOKENS,
            messages=conversation_history
        )

        ai_text = response.content[0].text
        conversation_history.append({"role": "assistant", "content": ai_text})

        return client, conversation_history, ai_text

    except Exception as e:
        return None, [], f"AI interpretation unavailable: {e}"


# ══════════════════════════════════════════════════════════════════════════════
# MAIN SCANNER
# ══════════════════════════════════════════════════════════════════════════════

def run_scan(tickers):
    timestamp  = datetime.now().strftime("%Y-%m-%d %H:%M")
    market_ctx = load_market_context()

    print(f"\n{'=' * 65}")
    print(f"  SCANNER — {timestamp}")
    print(f"  Tickers: {', '.join(tickers)}")
    if market_ctx:
        print(f"  Context: {market_ctx.get('verdict', 'N/A')} | "
              f"VIX {market_ctx['vix']['current']:.1f} | "
              f"SPY {market_ctx['spy']['trend']}")
    print(f"{'=' * 65}")

    all_criteria = {}
    failed       = []

    for ticker in tickers:
        print(f"\n  {ticker}...", end=" ", flush=True)
        try:
            criteria = get_all_criteria(ticker)
            if criteria is None:
                print("no data")
                failed.append(ticker)
                continue

            # Save to DB (scored version for monitor compatibility)
            from scoring import score_criteria
            scored = score_criteria(criteria)
            if scored:
                analysis_id = save_analysis(scored)
                scored["analysis_id"] = analysis_id

            all_criteria[ticker] = criteria
            print(f"OK ${criteria.get('price', '?'):.2f}")

        except Exception as e:
            print(f"ERROR {e}")
            failed.append(ticker)

    if not all_criteria:
        print("\n  No tickers analyzed.")
        return

    if failed:
        print(f"\n  Failed: {', '.join(failed)}")

    # ── AI interpretation ──────────────────────────────────────────────────────
    open_positions = get_open_positions()
    client, conversation_history, ai_text = get_ai_interpretation(
        all_criteria, open_positions, market_ctx, TRADING_CONTEXT
    )

    # ── Build scored_list for report ───────────────────────────────────────────
    from report_generator import generate_report, is_no_trade

    scored_list = []
    for ticker, data in all_criteria.items():
        tech   = data.get("technical", {})
        vol    = data.get("volatility", {})
        earn   = data.get("earnings", {})
        fund   = data.get("fundamental", {})
        ma     = tech.get("moving_averages", {})
        trend  = tech.get("trend_25d", {})
        w52    = tech.get("week_52", {})
        sr     = tech.get("support_resistance", {})
        candle = tech.get("candlestick", {})

        criteria_scores = {
            "trend_25d":     {"label": f"{'BULLISH' if trend.get('is_bullish') else 'BEARISH'} ({trend.get('pct_change', 0):+.1f}%)", "score": 0},
            "moving_averages": {"label": f"{'Above both' if ma.get('above_sma50') and ma.get('above_sma200') else 'Above SMA50' if ma.get('above_sma50') else 'Below both'} | SMA50 {ma.get('sma50_direction', 'N/A')}", "score": 0},
            "rsi":           {"label": f"{tech.get('rsi', 'N/A'):.1f}" if isinstance(tech.get('rsi'), (int, float)) else "N/A", "score": 0},
            "week_52":       {"label": f"{w52.get('position_pct', 0):.1f}% ({w52.get('tag', '')})", "score": 0},
            "support":       {"label": f"{sr.get('support_pct', 0):.1f}% away" if sr.get('support_pct') is not None else "N/A", "score": 0},
            "resistance":    {"label": f"{sr.get('resistance_pct', 0):.1f}% away" if sr.get('resistance_pct') is not None else "N/A", "score": 0},
            "candlestick":   {"label": f"{candle.get('pattern', 'N/A')} ({candle.get('sentiment', 'N/A')})", "score": 0},
            "hv_30d":        {"label": f"{vol.get('hv_30d', 0):.1f}%" if isinstance(vol.get('hv_30d'), (int, float)) else "N/A", "score": 0},
            "iv":            {"label": f"{vol.get('iv', 0):.1f}% (P{vol.get('iv_percentile', 0):.0f})" if isinstance(vol.get('iv'), (int, float)) and isinstance(vol.get('iv_percentile'), (int, float)) else "N/A", "score": 0},
            "beta":          {"label": f"{vol.get('beta', 0):.2f}" if isinstance(vol.get('beta'), (int, float)) else "N/A", "score": 0},
            "put_call_ratio": {"label": f"{vol.get('put_call_ratio', 0):.2f}" if isinstance(vol.get('put_call_ratio'), (int, float)) else "N/A", "score": 0},
            "open_interest": {"label": f"{vol.get('open_interest', 0):,.0f}" if isinstance(vol.get('open_interest'), (int, float)) else "N/A", "score": 0},
            "earnings":      {"label": f"{earn.get('days_to_earnings', 'N/A')}d" if earn.get('days_to_earnings') else "ETF" if earn.get('is_etf') else "N/A", "score": 0},
            "volume":        {"label": f"{data.get('volume', {}).get('volume_ratio_pct', 0):.0f}% of avg", "score": 0},
            "pe":            {"label": f"{fund.get('pe', 'N/A'):.1f}" if isinstance(fund.get('pe'), (int, float)) else "N/A", "score": 0},
            "eps_growth":    {"label": f"{fund.get('eps_growth_pct', 0):+.1f}%" if isinstance(fund.get('eps_growth_pct'), (int, float)) else "N/A", "score": 0},
            "debt_equity":   {"label": f"{fund.get('debt_to_equity', 0):.2f}x" if isinstance(fund.get('debt_to_equity'), (int, float)) else "N/A", "score": 0},
            "profit_margin": {"label": f"{fund.get('profit_margin_pct', 0):.1f}%" if isinstance(fund.get('profit_margin_pct'), (int, float)) else "N/A", "score": 0},
        }

        scored_list.append({
            "ticker":          ticker,
            "price":           data.get("price", 0),
            "score":           0,
            "score_max":       0,
            "score_pct":       0,
            "verdict":         "ANALYZED",
            "criteria_scores": criteria_scores,
        })

    # ── Filter actionable tickers (not "No trade") for markdown ───────────────
    actionable_list = [
        s for s in scored_list
        if not is_no_trade(ai_text, s["ticker"])
    ]

    print(f"\n  Actionable: {len(actionable_list)} de {len(scored_list)} tickers")

    # ── Generate reports ───────────────────────────────────────────────────────
    md_path, html_path = generate_report(
        all_scored=scored_list,
        actionable=actionable_list,
        ai_text=ai_text,
        market_context=market_ctx
    )

    import webbrowser
    webbrowser.open(f"file:///{html_path.replace(os.sep, '/')}")

    # ── Conversation loop ──────────────────────────────────────────────────────
    if client:
        print("\n  Ask me about the analysis. Type 'exit' to quit.\n")
        while True:
            user_input = input("Your question: ").strip()
            if not user_input:
                continue
            if user_input.lower() == "exit":
                break

            conversation_history.append({"role": "user", "content": user_input})
            follow_up = client.messages.create(
                model=AI_MODEL,
                max_tokens=AI_MAX_TOKENS,
                messages=conversation_history
            )
            ai_reply = follow_up.content[0].text
            conversation_history.append({"role": "assistant", "content": ai_reply})
            print(f"\n  {ai_reply}\n")

    print(f"\n  Scan complete: {len(all_criteria)} analyzed | {len(failed)} failed")
    print(f"  Markdown:  {md_path}")
    print(f"  HTML:      {html_path}\n")


# ══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Options opportunity scanner")
    parser.add_argument("--tickers", nargs="+", default=None)
    parser.add_argument("--context", action="store_true",
                        help="Use tickers from market_context.json")
    args = parser.parse_args()

    if args.context:
        ctx = load_market_context()
        if ctx and ctx.get("recommended_tickers"):
            tickers = ctx["recommended_tickers"]
            print(f"  Context mode: {len(tickers)} tickers from priority sectors")
        else:
            print("  market_context.json not found — run market_context.py first")
            print("  Falling back to default tickers")
            tickers = DEFAULT_TICKERS
    elif args.tickers:
        tickers = args.tickers
    else:
        tickers = DEFAULT_TICKERS

    run_scan(tickers)