"""
scanner.py
==========
Market opportunity scanner — simplified, no internal AI.

Workflow:
    1. Reads market_context.json (generated by market_context.py)
    2. Fetches raw criteria for each ticker via criteria.py
    3. Applies 5 hard filters (passes_hard_filters)
    4. Runs option_selector.py for tickers that pass filters
    5. Saves criteria to PostgreSQL
    6. Generates scanner_report.md (for AI interpretation) +
                   scanner_report.html (for browser)

No AI interpretation inside scanner — markdown is passed to Claude directly.

Usage:
    python scanner.py                          # default tickers
    python scanner.py --tickers AAPL MSFT CAT  # specific tickers
    python scanner.py --context                # tickers from market_context.json

Dependencies:
    criteria.py         → raw market data + hard filters
    option_selector.py  → strike selection via Tastytrade API
    db.py               → save to PostgreSQL
    report_generator.py → markdown + HTML reports
    market_context.json → macro context from market_context.py
"""

import os
import sys
import json
import argparse
import webbrowser
from datetime import datetime

from dotenv import load_dotenv
from tastytrade import Session

from criteria import get_all_criteria, passes_hard_filters
from option_selector import get_options_for_tickers
from db import save_analysis, get_open_positions
from scoring import score_criteria

load_dotenv()
sys.stdout.reconfigure(encoding="utf-8")


# ══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ══════════════════════════════════════════════════════════════════════════════

DEFAULT_TICKERS = [
    "SLB", "HAL", "XOM", "OKE", "VLO", "MPC", "PSX", "TRGP",
    "STLD", "IFF", "VMC", "PPG", "APD", "DD", "CTVA", "AMCR",
    "EVRG", "NI", "AES", "FE", "ATO", "AEP", "AEE", "EIX",
    "CAT", "CMI", "GNRC", "FIX", "EME", "HII", "VRT", "RTX",
]

MARKET_CONTEXT_JSON = os.path.join(os.path.dirname(__file__), "market_context.json")
REPORT_MD_PATH      = os.path.join(os.path.dirname(__file__), "scanner_report.md")
REPORT_HTML_PATH    = os.path.join(os.path.dirname(__file__), "scanner_report.html")


# ══════════════════════════════════════════════════════════════════════════════
# MARKET CONTEXT
# ══════════════════════════════════════════════════════════════════════════════

def load_market_context():
    if not os.path.exists(MARKET_CONTEXT_JSON):
        return None
    with open(MARKET_CONTEXT_JSON) as f:
        return json.load(f)


def format_market_context_md(ctx):
    if not ctx:
        return "Market context not available — run market_context.py first.\n"
    vix     = ctx.get("vix", {})
    spy     = ctx.get("spy", {})
    verdict = ctx.get("verdict", "N/A")
    detail  = ctx.get("verdict_detail", "")
    lines   = [
        f"## Contexto Macro",
        f"**Verdict:** {verdict} — {detail}",
        f"**VIX:** {vix.get('current', 'N/A')} ({vix.get('level', 'N/A')}, {vix.get('trend', 'N/A')})",
        f"**SPY:** ${spy.get('price', 'N/A')} | {spy.get('trend', 'N/A')} ({spy.get('pct_25d', 0):+.1f}% 25d)",
    ]
    sectors = ctx.get("sectors", [])
    if sectors:
        lines.append("\n**Sectores (win rates históricos):**")
        for s in sectors:
            icon = "✅" if s["priority"] == "PRIORITY" else \
                   "⚠️" if s["priority"] == "ACCEPTABLE" else "❌"
            lines.append(f"- {icon} {s['sector']}: {s['win_rate']:.1f}% [{s['priority']}]")
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# OPEN POSITIONS FORMATTER
# ══════════════════════════════════════════════════════════════════════════════

def format_open_positions_md(positions):
    if not positions:
        return "## Posiciones Abiertas\nNinguna.\n"
    lines = ["## Posiciones Abiertas", ""]
    for p in positions:
        lines.append(
            f"- **{p['ticker']}** {p['strategy']} | "
            f"${p['strike_low']}/{p['strike_high']} | "
            f"Exp {p['expiration']} | "
            f"Costo ${p['total_cost']}"
        )
    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# CRITERIA FORMATTER — for markdown report
# ══════════════════════════════════════════════════════════════════════════════

def format_criteria_md(ticker, criteria):
    """Format raw criteria as compact markdown section."""
    tech = criteria.get("technical", {})
    vol  = criteria.get("volatility", {})
    earn = criteria.get("earnings", {})
    fund = criteria.get("fundamental", {})
    volm = criteria.get("volume", {})

    trend  = tech.get("trend_25d", {})
    ma     = tech.get("moving_averages", {})
    rsi    = tech.get("rsi")
    w52    = tech.get("week_52", {})
    sr     = tech.get("support_resistance", {})
    candle = tech.get("candlestick", {})

    lines = [f"### {ticker} — ${criteria.get('price', 0):.2f}", ""]

    # Technical
    lines.append("**Technical:**")
    direction = "BULLISH" if trend.get("is_bullish") else "BEARISH"
    lines.append(f"- Trend 25d: {direction} ({trend.get('pct_change', 0):+.1f}%)")
    above = "Above both" if ma.get("above_sma50") and ma.get("above_sma200") \
            else "Above SMA50" if ma.get("above_sma50") else "Below both"
    lines.append(f"- MAs: {above} | SMA50 {ma.get('sma50_direction', 'N/A')}")
    lines.append(f"- RSI: {rsi:.1f}" if rsi else "- RSI: N/A")
    lines.append(f"- 52w: {w52.get('position_pct', 0):.1f}% ({w52.get('tag', '')})")
    sup = sr.get("support_pct")
    res = sr.get("resistance_pct")
    lines.append(f"- Support: {sup:.1f}% away" if sup is not None else "- Support: N/A")
    lines.append(f"- Resistance: {res:.1f}% away" if res is not None else "- Resistance: N/A")
    lines.append(f"- Candle: {candle.get('pattern', 'N/A')} ({candle.get('sentiment', 'N/A')})")

    # Volatility
    iv    = vol.get("iv")
    ivp   = vol.get("iv_percentile")
    ivr   = vol.get("iv_rank")
    hv    = vol.get("hv_30d")
    ivhv  = vol.get("iv_hv_diff")
    beta  = vol.get("beta")
    pcr   = vol.get("put_call_ratio")
    oi    = vol.get("open_interest")
    liq   = vol.get("liquidity_rating")

    lines.append("\n**Volatility:**")
    lines.append(f"- IV: {iv:.1f}% (P{ivp:.0f} / Rank {ivr:.2f})" if all(x is not None for x in [iv, ivp, ivr]) else "- IV: N/A")
    lines.append(f"- HV 30d: {hv:.1f}% | IV-HV: {ivhv:+.1f}%" if all(x is not None for x in [hv, ivhv]) else "- HV: N/A")
    lines.append(f"- Beta: {beta:.2f}" if beta is not None else "- Beta: N/A")
    lines.append(f"- Put/Call: {pcr:.2f}" if pcr is not None else "- Put/Call: N/A")
    lines.append(f"- OI (ATM): {oi:,.0f}" if oi is not None else "- OI: N/A")
    lines.append(f"- Liquidity: {liq}/5" if liq is not None else "- Liquidity: N/A")

    # Operational
    days_earn = earn.get("days_to_earnings")
    vol_ratio = volm.get("volume_ratio_pct", 0)
    lines.append("\n**Operational:**")
    lines.append(f"- Earnings: {days_earn}d" if days_earn else "- Earnings: ETF" if earn.get("is_etf") else "- Earnings: N/A")
    lines.append(f"- Volume: {vol_ratio:.0f}% of avg")

    # Fundamental
    pe     = fund.get("pe")
    eps_g  = fund.get("eps_growth_pct")
    de     = fund.get("debt_to_equity")
    margin = fund.get("profit_margin_pct")
    lines.append("\n**Fundamental:**")
    lines.append(f"- PE: {pe:.1f}x" if pe is not None else "- PE: N/A")
    lines.append(f"- EPS growth: {eps_g:+.1f}%" if eps_g is not None else "- EPS growth: N/A")
    lines.append(f"- Debt/Equity: {de:.2f}x" if de is not None else "- Debt/Equity: N/A")
    lines.append(f"- Profit margin: {margin:.1f}%" if margin is not None else "- Profit margin: N/A")

    return "\n".join(lines)


# ══════════════════════════════════════════════════════════════════════════════
# REPORT GENERATORS
# ══════════════════════════════════════════════════════════════════════════════

def generate_markdown(market_ctx, open_positions, passed_criteria, options_md, eliminated):
    """
    Generate scanner_report.md for Claude interpretation.
    Contains: macro context, open positions, criteria for passed tickers,
              option selector results, and eliminated tickers summary.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append(f"# Scanner Report — {timestamp}")
    lines.append("")
    lines.append(format_market_context_md(market_ctx))
    lines.append("")
    lines.append(format_open_positions_md(open_positions))
    lines.append("")

    # Passed tickers — full criteria
    if passed_criteria:
        lines.append(f"## Tickers que pasaron filtros ({len(passed_criteria)})")
        lines.append("")
        for ticker, criteria in passed_criteria.items():
            lines.append(format_criteria_md(ticker, criteria))
            lines.append("")
    else:
        lines.append("## Tickers que pasaron filtros")
        lines.append("")
        lines.append("_Ningún ticker pasó los 5 filtros duros hoy._")
        lines.append("")

    # Option selector results
    if options_md:
        lines.append("## Option Selector — Strikes Recomendados")
        lines.append("")
        lines.append(options_md)
        lines.append("")

    # Eliminated tickers — summary only
    if eliminated:
        lines.append(f"## Eliminados por Filtros Duros ({len(eliminated)})")
        lines.append("")
        for ticker, reasons in eliminated.items():
            lines.append(f"- **{ticker}:** {' | '.join(reasons)}")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generado {timestamp} · Options Trading System_")

    content = "\n".join(lines)
    with open(REPORT_MD_PATH, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  Markdown → {REPORT_MD_PATH}")
    return REPORT_MD_PATH


def generate_html(market_ctx, open_positions, passed_criteria,
                  eliminated, options_md, all_criteria):
    """Generate scanner_report.html — full detail for browser."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Build ticker cards
    def ticker_card(ticker, criteria, passed, reasons=None):
        price  = criteria.get("price", 0)
        tech   = criteria.get("technical", {})
        vol    = criteria.get("volatility", {})
        trend  = tech.get("trend_25d", {})
        ma     = tech.get("moving_averages", {})
        rsi    = tech.get("rsi")
        iv     = vol.get("iv")
        ivp    = vol.get("iv_percentile")

        border = "#22c55e" if passed else "#ef4444"
        tag    = "PASSED" if passed else "FILTERED"
        tag_bg = "#052e16" if passed else "#450a0a"
        reason_html = ""
        if reasons:
            reason_html = f'<div style="color:#ef4444;font-size:11px;margin-top:6px;">' + \
                          " | ".join(reasons) + "</div>"

        return f"""
        <div style="background:#111;border:1px solid {border}33;border-radius:10px;padding:16px;">
            <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
                <span style="font-size:20px;font-weight:900;color:#f9fafb;">{ticker}</span>
                <span style="font-size:12px;color:#9ca3af;">${price:.2f}</span>
                <span style="background:{tag_bg};border:1px solid {border};
                             border-radius:4px;padding:2px 8px;
                             color:{border};font-size:11px;font-weight:700;">{tag}</span>
            </div>
            <div style="font-size:12px;color:#6b7280;">
                {'BULLISH' if trend.get('is_bullish') else 'BEARISH'} {trend.get('pct_change', 0):+.1f}% |
                RSI {f"{rsi:.1f}" if rsi else 'N/A'} |
                IV {f"{iv:.1f}" if iv else 'N/A'}% (P{f"{ivp:.0f}" if ivp else 'N/A'}) |
                {'Above SMA50' if ma.get('above_sma50') else 'Below SMA50'}
            </div>
            {reason_html}
        </div>"""

    passed_cards = "".join(
        ticker_card(t, c, True)
        for t, c in passed_criteria.items()
    )
    eliminated_cards = "".join(
        ticker_card(t, all_criteria.get(t, {}), False, r)
        for t, r in eliminated.items()
    )

    # Market context banner
    verdict      = market_ctx.get("verdict", "N/A") if market_ctx else "N/A"
    verdict_color = "#22c55e" if verdict == "FAVORABLE" else \
                    "#f59e0b" if verdict == "NEUTRAL"   else "#ef4444"
    vix_val = market_ctx["vix"]["current"] if market_ctx else "N/A"
    spy_val = market_ctx["spy"]["price"]   if market_ctx else "N/A"
    spy_trend = market_ctx["spy"]["trend"] if market_ctx else "N/A"

    # Open positions
    pos_html = ""
    if open_positions:
        for p in open_positions:
            pos_html += f"""
            <div style="background:#1a1a1a;border-radius:8px;padding:12px 16px;margin-bottom:8px;">
                <span style="color:#f9fafb;font-weight:700;">{p['ticker']}</span>
                <span style="color:#6b7280;font-size:12px;margin-left:8px;">
                    {p['strategy']} ${p['strike_low']}/{p['strike_high']} |
                    Exp {p['expiration']} | Costo ${p['total_cost']}
                </span>
            </div>"""
    else:
        pos_html = '<div style="color:#6b7280;font-size:13px;">Ninguna posición abierta.</div>'

    # Options markdown → simple pre block
    options_html = f'<pre style="color:#cbd5e1;font-size:12px;white-space:pre-wrap;line-height:1.6;">{options_md}</pre>' \
                   if options_md else '<div style="color:#6b7280;">No hay strikes disponibles.</div>'

    html = f"""<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scanner — {timestamp}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            background: #0a0a0a; color: #f9fafb;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            padding: 32px 24px;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .section {{ margin-bottom: 40px; }}
        .section-title {{
            font-size: 11px; font-weight: 700; letter-spacing: 3px;
            color: #6b7280; text-transform: uppercase;
            margin-bottom: 16px; padding-bottom: 8px;
            border-bottom: 1px solid #1e1e1e;
        }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 12px; }}
        .card {{ background: #111; border: 1px solid #1e1e1e; border-radius: 10px; padding: 20px; }}
    </style>
</head>
<body>
<div class="container">

    <div style="margin-bottom:32px;padding-bottom:24px;border-bottom:1px solid #1e1e1e;">
        <h1 style="font-size:28px;font-weight:900;letter-spacing:-1px;">Options Scanner</h1>
        <p style="color:#6b7280;font-size:13px;font-family:monospace;margin-top:4px;">{timestamp}</p>
    </div>

    <!-- MARKET CONTEXT -->
    <div class="section">
        <div class="section-title">Contexto Macro</div>
        <div class="card" style="border-color:{verdict_color}33;">
            <div style="display:flex;align-items:center;gap:10px;margin-bottom:16px;">
                <div style="width:10px;height:10px;border-radius:50%;background:{verdict_color};"></div>
                <span style="font-size:18px;font-weight:900;color:{verdict_color};">{verdict}</span>
            </div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
                <div>
                    <div style="font-size:10px;color:#6b7280;letter-spacing:2px;">VIX</div>
                    <div style="font-size:24px;font-weight:900;">{vix_val}</div>
                </div>
                <div>
                    <div style="font-size:10px;color:#6b7280;letter-spacing:2px;">SPY</div>
                    <div style="font-size:24px;font-weight:900;">${spy_val}</div>
                    <div style="font-size:12px;color:#22c55e;">{spy_trend}</div>
                </div>
            </div>
        </div>
    </div>

    <!-- OPEN POSITIONS -->
    <div class="section">
        <div class="section-title">Posiciones Abiertas</div>
        {pos_html}
    </div>

    <!-- PASSED TICKERS -->
    <div class="section">
        <div class="section-title">Pasaron Filtros ({len(passed_criteria)})</div>
        <div class="grid">{passed_cards if passed_cards else '<div style="color:#6b7280;">Ninguno.</div>'}</div>
    </div>

    <!-- OPTION SELECTOR -->
    <div class="section">
        <div class="section-title">Option Selector — Strikes</div>
        <div class="card">{options_html}</div>
    </div>

    <!-- ELIMINATED -->
    <div class="section">
        <div class="section-title">Eliminados ({len(eliminated)})</div>
        <div class="grid">{eliminated_cards if eliminated_cards else '<div style="color:#6b7280;">Ninguno.</div>'}</div>
    </div>

    <div style="text-align:center;color:#374151;font-size:11px;
                padding:24px 0;border-top:1px solid #1e1e1e;font-family:monospace;">
        {timestamp} · Options Trading System · No AI inside scanner
    </div>

</div>
</body>
</html>"""

    with open(REPORT_HTML_PATH, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"  HTML    → {REPORT_HTML_PATH}")
    return REPORT_HTML_PATH


# ══════════════════════════════════════════════════════════════════════════════
# MAIN SCANNER
# ══════════════════════════════════════════════════════════════════════════════

def run_scan(tickers):
    timestamp  = datetime.now().strftime("%Y-%m-%d %H:%M")
    market_ctx = load_market_context()

    print(f"\n{'=' * 65}")
    print(f"  SCANNER — {timestamp}")
    print(f"  Tickers: {len(tickers)} | {', '.join(tickers[:8])}{'...' if len(tickers) > 8 else ''}")
    if market_ctx:
        print(f"  Context: {market_ctx.get('verdict', 'N/A')} | "
              f"VIX {market_ctx['vix']['current']:.1f} | "
              f"SPY {market_ctx['spy']['trend']}")
    print(f"{'=' * 65}\n")

    # ── Tastytrade session ─────────────────────────────────────────────────────
    tt_session = None
    try:
        tt_session = Session(
            os.getenv("TASTYTRADE_CLIENT_SECRET"),
            os.getenv("TASTYTRADE_REFRESH_TOKEN")
        )
        print(f"  Tastytrade session: OK\n")
    except Exception as e:
        print(f"  Tastytrade session: FAILED ({e})\n")

    # ── Fetch criteria for all tickers ────────────────────────────────────────
    all_criteria  = {}
    passed_criteria = {}
    eliminated    = {}
    failed        = []

    for ticker in tickers:
        print(f"  {ticker}...", end=" ", flush=True)
        try:
            criteria = get_all_criteria(ticker)
            if criteria is None:
                print("no data")
                failed.append(ticker)
                continue

            all_criteria[ticker] = criteria

            # Apply hard filters
            passed, reasons = passes_hard_filters(criteria)
            if passed:
                passed_criteria[ticker] = criteria
                print(f"OK ${criteria['price']:.2f} ✓ PASSED")
            else:
                eliminated[ticker] = reasons
                print(f"OK ${criteria['price']:.2f} ✗ {reasons[0]}")

            # Save to DB
            try:
                scored = score_criteria(criteria)
                if scored:
                    analysis_id = save_analysis(scored)
                    scored["analysis_id"] = analysis_id
            except Exception:
                pass

        except Exception as e:
            print(f"ERROR {e}")
            failed.append(ticker)

    print(f"\n  {'=' * 50}")
    print(f"  Analyzed: {len(all_criteria)} | Passed: {len(passed_criteria)} | "
          f"Eliminated: {len(eliminated)} | Failed: {len(failed)}")

    # ── Option selector for passed tickers ────────────────────────────────────
    options_md = ""
    if passed_criteria and tt_session:
        print(f"\n  Running option_selector for {len(passed_criteria)} tickers...")
        options_md = get_options_for_tickers(tt_session, passed_criteria)
    elif not passed_criteria:
        print(f"\n  No tickers passed filters — skipping option_selector")
    elif not tt_session:
        print(f"\n  No Tastytrade session — skipping option_selector")

    # ── Open positions ─────────────────────────────────────────────────────────
    open_positions = get_open_positions()

    # ── Generate reports ───────────────────────────────────────────────────────
    print(f"\n  Generating reports...")
    md_path   = generate_markdown(market_ctx, open_positions, passed_criteria, options_md, eliminated)
    html_path = generate_html(market_ctx, open_positions, passed_criteria, eliminated, options_md, all_criteria)

    print(f"\n{'=' * 65}")
    print(f"  SCAN COMPLETE")
    print(f"  Passed filters:  {len(passed_criteria)} tickers")
    print(f"  Markdown:        {md_path}")
    print(f"  HTML:            {html_path}")
    if failed:
        print(f"  Failed:          {', '.join(failed)}")
    print(f"{'=' * 65}\n")

    webbrowser.open(f"file:///{html_path.replace(os.sep, '/')}")


# ══════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Options opportunity scanner")
    parser.add_argument("--tickers", nargs="+", default=None)
    parser.add_argument("--context", action="store_true",
                        help="Use tickers from market_context.json (legacy, 32 tickers)")
    parser.add_argument("--universe", action="store_true",
                        help="Scan full S&P 500 with fast pre-filter")
    parser.add_argument("--no-cache", action="store_true",
                        help="Force re-fetch of S&P 500 list (ignore cache)")
    args = parser.parse_args()

    if args.universe:
        from universe import get_scanner_candidates
        print("\n  UNIVERSE MODE — scanning full S&P 500 with pre-filter\n")
        tickers = get_scanner_candidates(use_cache=not args.no_cache)
        if not tickers:
            print("  Could not build universe — falling back to defaults")
            tickers = DEFAULT_TICKERS
    elif args.context:
        ctx = load_market_context()
        if ctx and ctx.get("recommended_tickers"):
            tickers = ctx["recommended_tickers"]
            print(f"  Context mode: {len(tickers)} tickers from priority sectors")
        else:
            print("  market_context.json not found — falling back to defaults")
            tickers = DEFAULT_TICKERS
    elif args.tickers:
        tickers = args.tickers
    else:
        tickers = DEFAULT_TICKERS

    run_scan(tickers)